"""AUX-only cross-document migration. Never overwrites the signed v35 files.

prepare/validate: FreeCAD Python; integrate: FreeCAD GUI via MCP.
Geometry is copied with feature history, not regenerated by this script.
"""
from pathlib import Path
import hashlib
import json
import shutil
import sys

ROOT = Path(__file__).resolve().parents[2]
CAD = ROOT / "hardware/cad"
BASE = ROOT / "hardware/skorupa/v35"
TARGET = CAD / "assembly/RobotCat.FCStd"
PARAMS = CAD / "parameters/RobotParameters.FCStd"
BASE_HASH = "11e8c27e496032df6f556736e94699424723cef5fe0192b0ade2d152f810bdc5"
MASTER_HASH = "2eb5d64a63136815bf6e066ea753a9b96a07deae4db5eb8fdd496dea7200833f"
MODULES = {
    "chassis/Chassis": ["Deck35"],
    "shell/Shell": ["Shell35"],
    "tail/TailMount": ["TailBridge35"],
    "electronics/PowerMounts": ["Post35_0", "Post35_001", "Post35_2", "Post35_002"],
    "electronics/AuxPurchased": ["AuxReference35", "AuxTerminal35_0", "AuxTerminal35_1", "BoltM2x19", "NutM2"],
}


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def check_baseline():
    assert sha(BASE / "Kot_v35_ZASILANIE_AUX.FCStd") == BASE_HASH
    assert sha(BASE / "AuxPower35.FCStd") == MASTER_HASH


def document(A, path):
    assembly_module = str(Path(A.getHomePath()) / "Mod/Assembly")
    if assembly_module not in sys.path:
        sys.path.insert(0, assembly_module)
    return next((d for d in A.listDocuments().values() if d.FileName and Path(d.FileName).resolve() == path.resolve()), None) or A.openDocument(str(path))


def load_modules(A):
    document(A, PARAMS)
    return {name: document(A, CAD / "modules" / (name + ".FCStd")) for name in MODULES}


def bind_parameter_dependencies(A, modules):
    """App::Link autoloads the parameter doc; bare PropertyXLink did not."""
    var = document(A, PARAMS).getObject("AUX_mounting_interface")
    assert var is not None
    for name, doc in modules.items():
        if name == "electronics/AuxPurchased":
            continue
        obsolete = doc.getObject("InterfaceContract")
        if obsolete is not None:
            assert not obsolete.InList, "Do not remove a referenced interface"
            doc.removeObject(obsolete.Name)
        interface = doc.getObject("MountInterface") or doc.addObject("App::Link", "MountInterface")
        interface.setLink(var)
        interface.Label = "AUX interface - explicit external parameter dependency"
        if A.GuiUp:
            interface.Visibility = False
        doc.recompute()


def body_display(modules):
    """Render linked PartDesign Bodies by their tip, not hidden child features."""
    rows = []
    for doc in modules.values():
        for obj in doc.Objects:
            if obj.TypeId != "PartDesign::Body":
                continue
            modes = obj.ViewObject.getEnumerationsOfProperty("DisplayModeBody")
            assert "Tip" in modes, modes
            obj.ViewObject.DisplayModeBody = "Tip"
            obj.Visibility = True
            rows.append({"document": doc.Name, "body": obj.Name, "display": "Tip"})
    return rows


def assembly_parameters(A, doc):
    # Linked Bodies can be partially restored, skipping unreferenced objects
    # in their source document. The top-level anchor makes the parameter doc
    # an explicit assembly dependency, even when all module BReps are cached.
    var = document(A, PARAMS).getObject("AUX_mounting_interface")
    link = doc.getObject("MountParameters") or doc.addObject("App::Link", "MountParameters")
    link.setLink(var)
    link.Label = "Shared AUX parameters (not a physical component)"
    if A.GuiUp:
        link.Visibility = False


def write_report(name, report):
    out = CAD / "validation"
    out.mkdir(parents=True, exist_ok=True)
    (out / name).write_text(json.dumps(report, indent=2), encoding="utf-8", newline="\n")


def prepare():
    import FreeCAD as A
    check_baseline()
    source = A.openDocument(str(BASE / "AuxPower35.FCStd"))
    for module, objects in MODULES.items():
        path = CAD / "modules" / (module + ".FCStd")
        assert not path.exists(), f"Preserve {path}"
        path.parent.mkdir(parents=True, exist_ok=True)
        target = A.newDocument(path.stem)
        for name in objects:
            src = source.getObject(name)
            dst = target.copyObject(src, True)
            assert dst.Name == name, (name, dst.Name)
            dst.addProperty("App::PropertyString", "MigrationSource", "Traceability")
            dst.MigrationSource = "v35/AuxPower35.FCStd#" + name
            dst.addProperty("App::PropertyString", "MigrationScope", "Traceability")
            dst.MigrationScope = "AUX interface pilot only; inherited bases are not rebuilt parametric masters."
        target.recompute()
        target.saveAs(str(path))
        A.closeDocument(target.Name)
    A.closeDocument(source.Name)
    check_baseline()
    print("Prepared five independent owner documents; no assembly changed.", flush=True)


def mappings():
    sys.path.insert(0, str(ROOT / "tools/freecad/skorupa"))
    from aux35 import ADDITIONS, REPLACEMENTS
    owner = {obj: module for module, objs in MODULES.items() for obj in objs}
    # Legacy labels differ from the internal names after duplicate_object.
    owner.update({"Post35_1": "electronics/PowerMounts", "Post35_3": "electronics/PowerMounts"})
    result = {n: (owner[src], src, xyz) for n, (src, xyz) in REPLACEMENTS.items()}
    result.update({n: (owner[src], src, xyz) for n, (src, _, _, xyz) in ADDITIONS.items()})
    return result


def global_shape(obj):
    shape = obj.Shape.copy()
    if hasattr(obj, "getGlobalPlacement"):
        shape.Placement = obj.getGlobalPlacement() * obj.Placement.inverse() * shape.Placement
    else:
        # App::Link is a DocumentObject rather than Part::Feature. Its Shape
        # already carries LinkPlacement, but not the containing rigid frame.
        parent = obj.Document.getObject("Rigid_" + obj.Name)
        assert parent is not None and obj in parent.Group, obj.Name
        shape.Placement = parent.getGlobalPlacement() * shape.Placement
    return shape


def integrate():
    import FreeCAD as A
    import FreeCADGui as G
    check_baseline()
    assert not TARGET.exists(), "Preserve existing development assembly"
    modules = load_modules(A)
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    bind_parameter_dependencies(A, modules)
    body_display(modules)
    shutil.copy2(BASE / "Kot_v35_ZASILANIE_AUX.FCStd", TARGET)
    d = A.openDocument(str(TARGET))
    assembly_parameters(A, d)
    rows = []
    for name, (owner, src_name, xyz) in mappings().items():
        old = d.getObject(name)
        before = global_shape(old)
        label = old.Label
        color = old.ViewObject.ShapeColor
        diffuse = old.ViewObject.DiffuseColor
        metadata = {key: getattr(old, key) for key in ["MaterialSpec", "RigidStage", "DesignStatus"] if key in old.PropertiesList}
        parent = d.getObject("Rigid_" + name)
        source = modules[owner].getObject(src_name)
        if source is None:
            matches = modules[owner].getObjectsByLabel(src_name)
            assert len(matches) == 1
            source = matches[0]
        # A Link has ViewProviderLink, not the ShapeColor interface of a Part.
        # The source owns appearance; each link inherits it.
        source.ViewObject.ShapeColor = color
        source.ViewObject.DiffuseColor = diffuse
        d.removeObject(name)
        link = d.addObject("App::Link", name)
        assert link.Name == name
        link.setLink(source)
        parent.addObject(link)
        # LinkTransform=False replaces the source object Placement. Establish
        # the instance transform from actual shapes, not display labels.
        link.LinkTransform = False
        d.recompute()
        link.LinkPlacement = before.Placement * link.Shape.Placement.inverse()
        for key, value in metadata.items():
            if key not in link.PropertiesList:
                link.addProperty("App::PropertyString", key, "Traceability")
            setattr(link, key, value)
        link.Label = label
        link.Visibility = True
        rows.append({"component": name, "module": owner, "object": source.Name})
        print("Linked " + name, flush=True)
    d.Label = "Robot cat - modular AUX pilot - PROTOTYPE"
    plan = json.loads((BASE / "assembly-plan.json").read_text())
    for row in plan["components"]:
        d.getObject("Rigid_" + row["name"]).Visibility = True
        obj = d.getObject(row["name"])
        obj.Visibility = True
        view = obj.LinkedObject.ViewObject if obj.TypeId == "App::Link" else obj.ViewObject
        if "Transparency" in view.PropertiesList:
            view.Transparency = 0
        if obj.TypeId == "App::Link":
            obj.LinkedObject.Visibility = True
    d.recompute()
    assert d.getObject("RobotCatAssembly24").solve() == 0
    for doc in modules.values():
        doc.save()
    d.save()
    write_report("link-map.json", {"baseline_sha256": BASE_HASH, "links": rows})
    for module in modules.values():
        G.getDocument(module.Name).activeView().viewAxonometric()
    A.setActiveDocument(d.Name)
    G.activeDocument().activeView().viewAxonometric()
    G.activeDocument().activeView().fitAll()
    check_baseline()
    print(json.dumps({"assembly": str(TARGET), "external_links": len(rows)}))


def compare():
    """Fresh-process global BRep comparison; no Boolean repair or alignment."""
    import FreeCAD as A
    sys.path.insert(0, str(ROOT / "tools/freecad/skorupa"))
    from inheritance30 import compare_text
    check_baseline()
    load_modules(A)
    d = document(A, TARGET)
    d.recompute()
    for name in mappings():
        obj = d.getObject(name)
        assert obj.TypeId == "App::Link" and obj.LinkedObject.Document != d, name
    plan = json.loads((BASE / "assembly-plan.json").read_text())
    assert len(plan["components"]) == 320 and len(plan["joints"]) == 319
    # Read signed CAD directly so a clean checkout needs no ignored BRep cache.
    source_doc = document(A, BASE / "Kot_v35_ZASILANIE_AUX.FCStd")
    rows = []
    for row in plan["components"]:
        name = row["name"]
        obj = d.getObject(name)
        assert obj is not None and not obj.Shape.isNull(), name
        expected = global_shape(source_doc.getObject(name))
        result = compare_text(expected.cleaned().exportBrepToString(), global_shape(obj).cleaned().exportBrepToString())
        rows.append({"name": name, **result})
    errors = [{"document": doc.Name, "object": obj.Name, "state": list(obj.State)}
              for doc in A.listDocuments().values() for obj in doc.Objects if "Invalid" in obj.State]
    report = {"baseline_sha256": BASE_HASH, "assembly_sha256": sha(TARGET),
              "components": len(rows), "external_links": len(mappings()),
              "comparison": "Cleaned BRep token comparison; no topology healing or alignment",
              "source_mode": "fresh signed baseline document; no untracked shape cache",
              "geometry": rows, "invalid_objects": errors,
              "mechanical_release": False}
    assert not errors, errors
    write_report("geometry.json", report)
    check_baseline()
    print(json.dumps({"components": len(rows), "max_delta": max(r["max_absolute_delta"] for r in rows)}))


def validate_native():
    import FreeCAD as A
    import math
    load_modules(A)
    d = document(A, TARGET)
    asm = d.getObject("RobotCatAssembly24")
    sim = d.getObject("RobotConnectionTest35")
    plan = json.loads((BASE / "assembly-plan.json").read_text())
    baseline = {r["name"]: d.getObject("Rigid_" + r["name"]).Placement.copy() for r in plan["components"]}
    assert all(p.isSame(A.Placement(), 1e-6) for p in baseline.values())
    local = {n: d.getObject(n).Placement.copy() for n in mappings()}
    rows, peaks = [], {}
    try:
        asm.generateSimulation(sim)
        assert asm.numberOfFrames() >= 20
        for i in range(asm.numberOfFrames()):
            asm.updateForFrame(i)
            gap = fixed = axis = 0.0
            for row in plan["joints"]:
                joint = d.getObject(row["name"])
                p = joint.Reference1[0].Placement * joint.Placement1
                q = joint.Reference2[0].Placement * joint.Placement2
                gap = max(gap, (p.Base - q.Base).Length)
                theta = (p.Rotation.inverted() * q.Rotation).Angle
                if row["type"] == "Fixed":
                    fixed = max(fixed, theta)
                else:
                    axis = max(axis, p.Rotation.multVec(A.Vector(0, 0, 1)).getAngle(q.Rotation.multVec(A.Vector(0, 0, 1))))
                    peaks[row["name"]] = max(peaks.get(row["name"], 0), math.degrees(theta))
            assert max(gap, fixed, axis) < 1e-5
            assert all(d.getObject(n).Placement.isSame(p, 1e-6) for n, p in local.items())
            assert all(d.getObject("Rigid_" + n).Placement.isSame(A.Placement(), 1e-6) for n in mappings())
            rows.append({"frame": i, "gap_mm": gap, "fixed_error_rad": fixed, "axis_error_rad": axis})
        assert abs(peaks["Rev_TailYaw29"] - 30) < 1e-5
        assert all(abs(v - 3) < 1e-5 for n, v in peaks.items() if n != "Rev_TailYaw29")
    finally:
        for name, pose in baseline.items():
            d.getObject("Rigid_" + name).Placement = pose
        d.recompute()
        assert asm.solve() == 0
    # Validation must not rewrite CAD (headless save would discard GUI state).
    report = {"assembly_sha256": sha(TARGET), "components": 320, "fixed": 306,
              "revolute": 13, "temporary": 29, "frames": rows, "peaks_deg": peaks,
              "restored": True, "physical_mounts_approved": False,
              "cad_saved": False, "module_sha256": {n: sha(CAD / "modules" / (n + ".FCStd")) for n in MODULES}}
    write_report("native-motion.json", report)
    check_baseline()
    print(json.dumps({"frames": len(rows), "temporary": 29, "restored": True}))


def parameter_test():
    """Fresh-process perturbation; restores values and never saves CAD inputs."""
    import FreeCAD as A
    check_baseline()
    modules = load_modules(A)
    param = document(A, PARAMS).getObject("AUX_mounting_interface")
    watched = [("chassis/Chassis", "Deck35", "DeckHoles35"),
               ("tail/TailMount", "TailBridge35", "BridgeHoles35"),
               ("electronics/PowerMounts", "Post35_0", "PostTallSketch35"),
               ("electronics/PowerMounts", "Post35_001", "PostTallSketch001"),
               ("electronics/PowerMounts", "Post35_2", "PostShortSketch35"),
               ("electronics/PowerMounts", "Post35_002", "PostShortSketch001")]
    before = {(module, body): modules[module].getObject(body).Shape.Volume for module, body, _ in watched}
    original = param.AuxHoleDiameter
    old = float(original)
    changes = []
    try:
        param.AuxHoleDiameter = old + 0.2
        param.Document.recompute()
        for doc in modules.values():
            doc.recompute()
        for module, body, sketch in watched:
            obj = modules[module].getObject(body)
            sk = modules[module].getObject(sketch)
            radii = [g.Radius for g in sk.Geometry]
            expected = (old + 0.2) / 2
            assert any(abs(r - expected) < 1e-8 for r in radii), (sketch, radii)
            assert sk.FullyConstrained and sk.solve() == 0
            delta = before[module, body] - obj.Shape.Volume
            assert delta > 0.01, (body, delta)
            changes.append({"module": module, "body": body, "radii_mm": radii,
                            "removed_volume_mm3": delta, "fully_constrained": True})
    finally:
        param.AuxHoleDiameter = original
        param.Document.recompute()
        for doc in modules.values():
            doc.recompute()
    for module, body, _ in watched:
        assert abs(modules[module].getObject(body).Shape.Volume - before[module, body]) < 1e-6
    report = {"parameter": "AuxHoleDiameter", "baseline_mm": old,
              "test_mm": old + 0.2, "restored": True,
              "changes": changes, "scope": "Clearance diameter only; not PCB hole pitch redesign.",
              "parameter_sha256": sha(PARAMS),
              "module_sha256": {n: sha(CAD / "modules" / (n + ".FCStd")) for n in MODULES}}
    write_report("parameter-update.json", report)
    check_baseline()
    print(json.dumps({"changed_bodies": len(changes), "restored": True}))


def relocation_test():
    """Run alone in a fresh FreeCAD Python process; only open relocated assembly."""
    import FreeCAD as A
    import tempfile
    assert not A.listDocuments(), "Relocation proof must start without cached documents"
    sys.path.insert(0, str(Path(A.getHomePath()) / "Mod/Assembly"))
    files = [PARAMS, TARGET] + [CAD / "modules" / (n + ".FCStd") for n in MODULES]
    hashes = {str(p.relative_to(CAD)).replace("\\", "/"): sha(p) for p in files}
    with tempfile.TemporaryDirectory(prefix="robot-cat-link-check-") as tmp:
        relocated = Path(tmp).resolve()
        for path in files:
            dst = relocated / path.relative_to(CAD)
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(path, dst)
        d = A.openDocument(str(relocated / "assembly/RobotCat.FCStd"))
        try:
            control = d.getObject("MountParameters")
            assert control is not None and control.TypeId == "App::Link"
            parameter = control.LinkedObject
            assert parameter is not None
            assert Path(parameter.Document.FileName).resolve().is_relative_to(relocated)
            d.recompute()
            solver_result = d.getObject("RobotCatAssembly24").solve()
            assert solver_result == 0, solver_result
            deps = []
            for name in mappings():
                link = d.getObject(name)
                assert link.TypeId == "App::Link" and not link.Shape.isNull(), name
                source = Path(link.LinkedObject.Document.FileName).resolve()
                assert source.is_relative_to(relocated), str(source)
                deps.append({"component": name, "resolved_file": source.relative_to(relocated).as_posix()})
            opened = list(A.listDocuments().values())
            assert len(opened) == 7, [(doc.Name, doc.FileName) for doc in opened]
            for doc in opened:
                assert Path(doc.FileName).resolve().is_relative_to(relocated), doc.FileName
                assert not any("Invalid" in obj.State for obj in doc.Objects), doc.Name
            post = d.getObject("AuxPost35_0")
            baseline_volume = post.Shape.Volume
            old_diameter = parameter.AuxHoleDiameter
            try:
                parameter.AuxHoleDiameter = float(old_diameter) + 0.2
                parameter.Document.recompute()
                for doc in opened:
                    if doc != d:
                        doc.recompute()
                d.recompute()
                assert post.Shape.Volume < baseline_volume - 0.01, "Relocated link did not update"
            finally:
                parameter.AuxHoleDiameter = old_diameter
                parameter.Document.recompute()
                for doc in opened:
                    if doc != d:
                        doc.recompute()
                d.recompute()
            assert abs(post.Shape.Volume - baseline_volume) < 1e-6
            assert all(sha(CAD / name) == digest for name, digest in hashes.items())
            report = {"fresh_process": True, "documents_loaded_through_links": len(opened),
                      "resolved_dependencies": deps, "file_sha256": hashes,
                      "source_paths_used": False, "solver_result": solver_result,
                      "relocated_parameter_update_restored": True, "passed": True}
        finally:
            for name in list(A.listDocuments()):
                A.closeDocument(name)
    write_report("relocation.json", report)
    print(json.dumps({"relocated_links": len(deps), "documents": len(opened)}))


if __name__ == "__main__":
    {"prepare": prepare, "compare": compare, "parameter-test": parameter_test,
     "relocation-test": relocation_test, "native-test": validate_native}[sys.argv[1]]()
